import { Signika } from "next/font/google";
import "./globals.css";
import Header from '@/components/header'

const signika = Signika({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={signika.className}>
      <Header />
        <div className="body-helper overflow-x-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
